### ISSUE TITLE
Differ::__construct(): Argument #1 ($outputBuilder) must be of type SebastianBergmann\Diff\Output\DiffOutputBuilderInterface, null given, 

### ISSUE THREAD

**Issue by umer936** [dereuromark/cakephp-ide-helper#306]
```
/templates/AllCounts
-> add
-> edit
-> index
2023-05-06 20:34:00 error: [TypeError] SebastianBergmann\Diff\Differ::__construct(): Argument #1 ($outputBuilder) must be of type SebastianBergmann\Diff\Output\DiffOutputBuilderInterface, null given, called in /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php on line 147 in /srv/http/vendor/sebastian/diff/src/Differ.php on line 40
Stack Trace:
- /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php:147
- /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/TemplateAnnotator.php:80
- /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/TemplateAnnotator.php:33
- /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php:442
- /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php:458
- /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php:406
- /srv/http/vendor/cakephp/cakephp/src/Console/Shell.php:500
- /srv/http/vendor/cakephp/cakephp/src/Console/CommandRunner.php:352
- /srv/http/vendor/cakephp/cakephp/src/Console/CommandRunner.php:169
- /srv/http/bin/cake.php:12

[TypeError] SebastianBergmann\Diff\Differ::__construct(): Argument #1 ($outputBuilder) must be of type SebastianBergmann\Diff\Output\DiffOutputBuilderInterface, null given, called in /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php on line 147 in /srv/http/vendor/sebastian/diff/src/Differ.php on line 40

Stack Trace:

#0 /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php(147): SebastianBergmann\Diff\Differ->__construct()
#1 /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/TemplateAnnotator.php(80): IdeHelper\Annotator\AbstractAnnotator->displayDiff()
#2 /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Annotator/TemplateAnnotator.php(33): IdeHelper\Annotator\TemplateAnnotator->annotateContent()
#3 /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php(442): IdeHelper\Annotator\TemplateAnnotator->annotate()
#4 /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php(458): IdeHelper\Shell\AnnotationsShell->_templates()
#5 /srv/http/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php(406): IdeHelper\Shell\AnnotationsShell->_templates()
#6 /srv/http/vendor/cakephp/cakephp/src/Console/Shell.php(500): IdeHelper\Shell\AnnotationsShell->templates()
#7 /srv/http/vendor/cakephp/cakephp/src/Console/CommandRunner.php(352): Cake\Console\Shell->runCommand()
#8 /srv/http/vendor/cakephp/cakephp/src/Console/CommandRunner.php(169): Cake\Console\CommandRunner->runShell()
#9 /srv/http/bin/cake.php(12): Cake\Console\CommandRunner->run()
#10 {main}
```

Template is a file from Bake. The fact that it's coming from "Diff" makes me question if it's the "<" for the iterable? 
```
<?php
/**
 * @var \App\View\AppView $this
 * @var iterable<\App\Model\Entity\AllCount> $allCounts
 */
?>
<div class="allCounts index content">
    <?= $this->Html->link(__('New All Count'), ['action' => 'add'], ['class' => 'button float-right']) ?>
    <h3><?= __('All Counts') ?></h3>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('id') ?></th>
                    <th><?= $this->Paginator->sort('files_id') ?></th>
                    <th><?= $this->Paginator->sort('SCLK_TIME') ?></th>
                    <th><?= $this->Paginator->sort('COUNT_RATE') ?></th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($allCounts as $allCount): ?>
                <tr>
                    <td><?= $this->Number->format($allCount->id) ?></td>
                    <td><?= $allCount->has('all_counts_file') ? $this->Html->link($allCount->all_counts_file->Array, ['controller' => 'AllCountsFiles', 'action' => 'view', $allCount->all_counts_file->id]) : '' ?></td>
                    <td><?= $this->Number->format($allCount->SCLK_TIME) ?></td>
                    <td><?= $this->Number->format($allCount->COUNT_RATE) ?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('View'), ['action' => 'view', $allCount->id]) ?>
                        <?= $this->Html->link(__('Edit'), ['action' => 'edit', $allCount->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $allCount->id], ['confirm' => __('Are you sure you want to delete # {0}?', $allCount->id)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>
```

**Comment by umer936** [comment]
DEBUG on `$newContent`, `$oldContent` in `vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php(147)`

```
########## DEBUG ##########
'<?php
/**
 * @var \App\View\AppView $this
 * @var iterable<\App\Model\Entity\AllCount> $allCounts
 */
?>
<div class="allCounts index content">
    <?= $this->Html->link(__('New All Count'), ['action' => 'add'], ['class' => 'button float-right']) ?>
    <h3><?= __('All Counts') ?></h3>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('id') ?></th>
                    <th><?= $this->Paginator->sort('files_id') ?></th>
                    <th><?= $this->Paginator->sort('SCLK_TIME') ?></th>
                    <th><?= $this->Paginator->sort('COUNT_RATE') ?></th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($allCounts as $allCount): ?>
                <tr>
                    <td><?= $this->Number->format($allCount->id) ?></td>
                    <td><?= $allCount->has('all_counts_file') ? $this->Html->link($allCount->all_counts_file->Array, ['controller' => 'AllCountsFiles', 'action' => 'view', $allCount->all_counts_file->id]) : '' ?></td>
                    <td><?= $this->Number->format($allCount->SCLK_TIME) ?></td>
                    <td><?= $this->Number->format($allCount->COUNT_RATE) ?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('View'), ['action' => 'view', $allCount->id]) ?>
                        <?= $this->Html->link(__('Edit'), ['action' => 'edit', $allCount->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $allCount->id], ['confirm' => __('Are you sure you want to delete # {0}?', $allCount->id)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>
'
###########################
ROOT/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php (line 149)
########## DEBUG ##########
'<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\AllCount[]|\Cake\Collection\CollectionInterface $allCounts
 */
?>
<div class="allCounts index content">
    <?= $this->Html->link(__('New All Count'), ['action' => 'add'], ['class' => 'button float-right']) ?>
    <h3><?= __('All Counts') ?></h3>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('id') ?></th>
                    <th><?= $this->Paginator->sort('files_id') ?></th>
                    <th><?= $this->Paginator->sort('SCLK_TIME') ?></th>
                    <th><?= $this->Paginator->sort('COUNT_RATE') ?></th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($allCounts as $allCount): ?>
                <tr>
                    <td><?= $this->Number->format($allCount->id) ?></td>
                    <td><?= $allCount->has('all_counts_file') ? $this->Html->link($allCount->all_counts_file->Array, ['controller' => 'AllCountsFiles', 'action' => 'view', $allCount->all_counts_file->id]) : '' ?></td>
                    <td><?= $this->Number->format($allCount->SCLK_TIME) ?></td>
                    <td><?= $this->Number->format($allCount->COUNT_RATE) ?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('View'), ['action' => 'view', $allCount->id]) ?>
                        <?= $this->Html->link(__('Edit'), ['action' => 'edit', $allCount->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $allCount->id], ['confirm' => __('Are you sure you want to delete # {0}?', $allCount->id)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>
'
###########################

```

**Comment by umer936** [comment]
Oops, this is a change in the diff library. I see the fixes are merged in the master branch. 
I changed my composer.json for now. 

https://github.com/sebastianbergmann/diff/pull/117#issuecomment-1529433063
