### ISSUE TITLE
Exception: ERROR: Referenced sniff "CakePHP" does not exist

### ISSUE THREAD

**Issue by ADmad** [dereuromark/cakephp-ide-helper#31]
Using CakePHP 3.5.0RC1 and idehelper v0.8.1:

```bash
$ bin/cake annotations controllers -p MyPlugin -d -v
/plugins/MyPlugin/src/Controller/
/plugins/MyPlugin/src/Controller/Manager/
-> MyPluginController.php
Exception: ERROR: Referenced sniff "CakePHP" does not exist

Run "phpcs --help" for usage information

 in [/srv/sites/mycms/vendor/squizlabs/php_codesniffer/src/Runner.php, line 298]
2017-08-05 12:28:05 Error: [PHP_CodeSniffer\Exceptions\DeepExitException] ERROR: Referenced sniff "CakePHP" does not exist

Run "phpcs --help" for usage information

 in /srv/sites/mycms/vendor/squizlabs/php_codesniffer/src/Runner.php on line 298
Stack Trace:
#0 /srv/sites/mycms/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php(103): PHP_CodeSniffer\Runner->init()
#1 /srv/sites/mycms/vendor/dereuromark/cakephp-ide-helper/src/Annotator/AbstractAnnotator.php(195): IdeHelper\Annotator\AbstractAnnotator->_getFile('/srv/sites/bcub...')
#2 /srv/sites/mycms/vendor/dereuromark/cakephp-ide-helper/src/Annotator/ControllerAnnotator.php(46): IdeHelper\Annotator\AbstractAnnotator->_annotate('/srv/sites/bcub...', '<?php\nnamespace...', Array)
#3 /srv/sites/mycms/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php(157): IdeHelper\Annotator\ControllerAnnotator->annotate('/srv/sites/bcub...')
#4 /srv/sites/mycms/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php(167): IdeHelper\Shell\AnnotationsShell->_controllers('/srv/sites/bcub...')
#5 /srv/sites/mycms/vendor/dereuromark/cakephp-ide-helper/src/Shell/AnnotationsShell.php(141): IdeHelper\Shell\AnnotationsShell->_controllers('/srv/sites/bcub...')
#6 /srv/sites/mycms/vendor/cakephp/cakephp/src/Console/Shell.php(493): IdeHelper\Shell\AnnotationsShell->controllers()
#7 /srv/sites/mycms/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#8 /srv/sites/mycms/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#9 /srv/sites/mycms/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#10 /srv/sites/mycms/bin/cake.php(22): Cake\Console\ShellDispatcher::run(Array)
#11 {main}
```

FYI I have `cakephp-codesniffer` globally installed through composer and default standard set to `CakePHP`.

**Comment by dereuromark** [comment]
Any idea on the fix here?
Never used the sniffer as global one.

**Comment by ADmad** [comment]
Where does your plugin code specify which standard to use?

**Comment by dereuromark** [comment]
It shouldnt, it doesnt at all:
https://github.com/dereuromark/cakephp-ide-helper/blob/master/src/Annotator/AbstractAnnotator.php#L99-L105

maybe that is part of the issue?

**Comment by dereuromark** [comment]
PR open.
