### ISSUE TITLE
Inline doc block issues

### ISSUE THREAD

**Issue by makallio85** [dereuromark/cakephp-ide-helper#57]
```
$ bin/cake annotations templates

Exception: Undefined offset: -1 in D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php:489. in [D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php, line 489]
2017-09-29 22:04:33 Error: [ErrorException] Undefined offset: -1 in D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php:489. in D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php on line 489
Stack Trace:
#0 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php(489): App\Console\ConsoleErrorHandler->handleError(8, 'Undefined offse...', 'D:\\xampp\\htdocs...', 489, Array)
#1 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php(284): IdeHelper\Annotator\AbstractAnnotator->_needsNewLineInDocBlock(Object(PHP_CodeSniffer\Files\File), 0)
#2 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\TemplateAnnotator.php(59): IdeHelper\Annotator\AbstractAnnotator->_appendToExistingDocBlock(Object(PHP_CodeSniffer\Files\File), 6, Array)
#3 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Annotator\TemplateAnnotator.php(36): IdeHelper\Annotator\TemplateAnnotator->_annotate('D:\\xampp\\htdocs...', '<?php\n/** @var ...', Array)
#4 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(197): IdeHelper\Annotator\TemplateAnnotator->annotate('D:\\xampp\\htdocs...')
#5 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(212): IdeHelper\Shell\AnnotationsShell->_templates('D:\\xampp\\htdocs...')
#6 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(212): IdeHelper\Shell\AnnotationsShell->_templates('D:\\xampp\\htdocs...')
#7 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(181): IdeHelper\Shell\AnnotationsShell->_templates('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\vuokravalvonta\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(92): IdeHelper\Shell\AnnotationsShell->templates()
#9 D:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Console\Shell.php(494): IdeHelper\Shell\AnnotationsShell->all()
#10 D:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#11 D:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#12 D:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#13 D:\xampp\htdocs\vuokravalvonta\bin\cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#14 {main}
```

**Comment by dereuromark** [comment]
Can you tell me what the file content is it tries to process?
Any details here maybe?

**Comment by makallio85** [comment]
Yeah sure, my bad. 

Seems defining doc block like this, causes that error:

```
<?php
/** @var \App\Lib\DocumentManager\DataFactory $DataFactory */
?>
```

Switching to this, solved the problem:

```
<?php
/**
 * @var \App\Lib\DocumentManager\DataFactory $DataFactory
 */
?>
```

**Comment by makallio85** [comment]
Exactly the same error appears, if you have this:

```
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<div class="row"></div>
```

Changing to this, fixes it:
```
<?php
/**
 * @var \App\View\AppView $this
 */
?>

<div class="row"></div>
```

**Comment by Kareylo** [comment]
Can you try with a empty file too?

**Comment by makallio85** [comment]
Empty file works just fine

**Comment by Kareylo** [comment]
When I tried with empty file, got the same error with `offset 0`

**Comment by dereuromark** [comment]
I will look into it for both cases :)

**Comment by dereuromark** [comment]
So what is your expectation? Should it autofix and expand this inline doc block?
Or should it add a new block on top?

**Comment by dereuromark** [comment]
PR open, please verify

**Comment by makallio85** [comment]
Original problem is gone, but new one occurs:

In empty template file this:

```
<?php
/** @var \App\Lib\DocumentManager\DataFactory $DataFactory */
?>
```

becomes to this:

```
<?php
/**
 * @var \App\View\AppView $this
 */
?>
```

**Comment by dereuromark** [comment]
Modifying an inline doc block at the same time is not that easy to do here.
We could either ignore that one, but could duplicate some annotations, or we must refactor that one before we start adding again..

**Comment by dereuromark** [comment]
I removed the removal in master for now, until we can figure sth out :)

**Comment by dereuromark** [comment]
OK, should be all good.
