### ISSUE TITLE
Exception: Directory name must not be empty

### ISSUE THREAD

**Issue by stmeyer** [dereuromark/cakephp-ide-helper#63]
I get this error:
```
> bin\cake annotations all

[Models]
Exception: Directory name must not be empty. in [...\vendor\squizlabs\php_codesniffer\src\Util\Standards.php, line 93]
2017-11-07 15:05:08 Error: [RuntimeException] Directory name must not be empty. in ...\vendor\squizlabs\php_codesniffer\src\Util\Standards.php on line 93
Stack Trace:
#0 ...\vendor\squizlabs\php_codesniffer\src\Util\Standards.php(93): DirectoryIterator->__construct('')
#1 ...\vendor\squizlabs\php_codesniffer\src\Runner.php(286): PHP_CodeSniffer\Util\Standards::getInstalledStandardDetails()
#2 ...\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php(114): PHP_CodeSniffer\Runner->init()
#3 ...\vendor\dereuromark\cakephp-ide-helper\src\Annotator\AbstractAnnotator.php(214): IdeHelper\Annotator\AbstractAnnotator->_getFile('...')
#4 ...\vendor\dereuromark\cakephp-ide-helper\src\Annotator\ModelAnnotator.php(112): IdeHelper\Annotator\AbstractAnnotator->_annotate('...', '<?php\n/**\n * Te...', Array)
#5 ...\vendor\dereuromark\cakephp-ide-helper\src\Annotator\ModelAnnotator.php(52): IdeHelper\Annotator\ModelAnnotator->_table('...', 'AssignComponent', Array)
#6 ...\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(134): IdeHelper\Annotator\ModelAnnotator->annotate('...')
#7 ...\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(110): IdeHelper\Shell\AnnotationsShell->_models('...')
#8 ...\vendor\dereuromark\cakephp-ide-helper\src\Shell\AnnotationsShell.php(92): IdeHelper\Shell\AnnotationsShell->models()
#9 ...\vendor\cakephp\cakephp\src\Console\Shell.php(492): IdeHelper\Shell\AnnotationsShell->all()
#10 ...\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#11 ...\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#12 ...\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#13 ...\bin\cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#14 {main}
```

**Comment by dereuromark** [comment]
Can you tell me what the content of that dictionary looks like? And what the name is?
So I can reproduce the issue?

Or do you have a PR in mind to fix this?

**Comment by stmeyer** [comment]
I could fix it by removing PHPCS configuration. If I change file `vendor\squizlabs\php_codesniffer\CodeSniffer.conf` from
```php
<?php
 $phpCodeSnifferConfig = array (
  'installed_paths' => './vendor/cakephp/cakephp-codesniffer',
)
?>
```
to
```php
<?php
 $phpCodeSnifferConfig = array ()
?>
```
IDE helper works without error

**Comment by dereuromark** [comment]
Sure, please make a PR.

**Comment by stmeyer** [comment]
Not shure how to fix. Is it a bug in PHPCS or IDE helper? Because I deleted **my local configuration** from PHPCS and not any source code 😄

**Comment by dereuromark** [comment]
It sounds like neither nor and a config issue on your side. Not sure what you are doing there, but it works for all other installations afaik.

**Comment by stmeyer** [comment]
Okay. Closing the issue. Thanks for your feedback.

**Comment by dereuromark** [comment]
Let me know if we can adjust the plugin in a way that it will work also with your setting.
